<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ClassSchedules [
  <!ELEMENT ClassSchedules (ClassSchedule)+>
  <!ELEMENT ClassSchedule (classID, startTime, endTime)>
  <!ELEMENT classID (#PCDATA)>
  <!ELEMENT startTime (#PCDATA)>
  <!ELEMENT endTime (#PCDATA)>
]>

<ClassSchedules>
  <!-- Each class id represents a different class type. Example: 2 = Yoga, 7 = Boxing, etc -->
  <ClassSchedule>
    <classID>7</classID>
    <startTime>2023-07-20 10:00</startTime>
    <endTime>2023-07-20 10:30</endTime>
  </ClassSchedule>

  <ClassSchedule>
    <classID>4</classID>
    <startTime>2023-07-20 11:00</startTime>
    <endTime>2023-07-20 12:00</endTime>
  </ClassSchedule>

  <ClassSchedule>
    <classID>6</classID>
    <startTime>2023-07-20 13:20</startTime>
    <endTime>2023-07-20 14:20</endTime>
  </ClassSchedule>
  
</ClassSchedules>